// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3zbYH6HdmILLfG-rTkbmQEqAa9uc1Ko',
    appId: '1:257285958535:web:ce54c9377cb83c32610122',
    messagingSenderId: '257285958535',
    projectId: 'expense-tracker-bdcf9',
    authDomain: 'expense-tracker-bdcf9.firebaseapp.com',
    storageBucket: 'expense-tracker-bdcf9.firebasestorage.app',
    measurementId: 'G-1N12PRKDEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEwE7oHB53E-N9maOpFMsO5NCYmxxKkDY',
    appId: '1:257285958535:android:82e21675c546c8f2610122',
    messagingSenderId: '257285958535',
    projectId: 'expense-tracker-bdcf9',
    storageBucket: 'expense-tracker-bdcf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCubZusSoApWe5dIEr5sd_W7geRe-I7IXQ',
    appId: '1:257285958535:ios:ace1b8ff5847c695610122',
    messagingSenderId: '257285958535',
    projectId: 'expense-tracker-bdcf9',
    storageBucket: 'expense-tracker-bdcf9.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
